version: '3'
services:
  api:
    container_name: server-container
    build: .
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=recombee
    volumes:
      - test_data:/var/lib/postgresql/data
volumes:
  test_data:
    external: true
